### ISSUE TITLE
Cp spike value

### ISSUE THREAD

**Issue by AdrianOlko** [MRod5/pyturb#16]
Spike value when you use cp(i) with i = 1000, (K)

![image](https://user-images.githubusercontent.com/71002945/189493114-eec75a42-ec9a-48b8-8969-096ca57d5c71.png)

\\ \\
from pyturb.gas_models import SemiperfectIdealGas
import numpy as np
import matplotlib.pyplot as plt 

t = np.linspace(200,3000)
cp = []
for i in t:
    cp0 = semiperfect_air.cp(i)
    cp.append(cp0)

plt.xlabel('K', fontsize=15)
plt.ylabel('c_p', fontsize=15)
plt.plot(t, cp)
plt.grid(True)
plt.show()
\\ \\

**Comment by MRod5** [comment]
Fixed
